# Generated by Django 4.0.1 on 2023-03-01 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Scan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('execution', models.CharField(choices=[('SCAN', 'Scan')], max_length=8)),
                ('ipv_type', models.CharField(blank=True, max_length=20, null=True)),
                ('scanner_type', models.CharField(max_length=20)),
                ('ip', models.GenericIPAddressField()),
                ('port', models.CharField(max_length=9)),
                ('result', models.CharField(blank=True, max_length=400, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('ERROR', 'Error'), ('SUCCESS', 'Success')], max_length=8)),
                ('message', models.CharField(blank=True, max_length=110)),
            ],
        ),
    ]
